### ISSUE TITLE
Pre-selection highlighting

### ISSUE THREAD

**Issue by mestaritonttu** [pasbi/ommpfritt#71]
When hovering the mouse over a point (or edge, if edge mode is accepted as a feature), it should be highlighted in a different colour/shade.

**Comment by pasbi** [comment]
This is already implemented, though I must admit that the hover-color is not vert well distinguishable from the default color.
You can change the color at runtime in "Edit" -> "Preferences" -> "Ui-Colors" -> "Handle" -> "Point".
The first column is for selected points, the second for unselected the third column is for hovered points.

Feel free to propose a better coloring scheme, you can change the default values in [ui-colors-dark.cfg](uicolors/ui-colors-dark.cfg) and [ui-colors-light.cfg](uicolors/ui-colors-light.cfg).

**Comment by mestaritonttu** [comment]
@pasbi I tried changing the colour at runtime, but I got a crash :)

```
terminate called after throwing an instance of 'std::out_of_range'
  what():  vector::_M_range_check: __n (which is 18446744073709551615) >= this->size() (which is 3)
```

**Comment by pasbi** [comment]
Ok really want to fix that bug, but I cannot reproduce it.
A stacktrace would be helpful.
Do you have a core dump or could you please try to reproduce the error in a debugger?

**Comment by mestaritonttu** [comment]
Core dump: https://gofile.io/d/3gK6bP

**Comment by pasbi** [comment]
Unfortunately, your core dump does not seem to be compatible with my binaries.
Can you run the application in a debugger and print the stacktrace? I'm quite sure where the crash occurs, but I have no clue where that huge value (`18446744073709551615`) comes from.
Don't hesitate to ask if you need assistance!

**Comment by mestaritonttu** [comment]
No problem, I have some experience debugging LibreOffice.

```
Thread 1 "ommpfritt" received signal SIGABRT, Aborted.
0x00007f2a08e74355 in raise () from /usr/lib/libc.so.6
(gdb) bt
#0  0x00007f2a08e74355 in raise () from /usr/lib/libc.so.6
#1  0x00007f2a08e5d853 in abort () from /usr/lib/libc.so.6
#2  0x00007f2a090af86a in __gnu_cxx::__verbose_terminate_handler () at /build/gcc/src/gcc/libstdc++-v3/libsupc++/vterminate.cc:95
#3  0x00007f2a090bbd8a in __cxxabiv1::__terminate (handler=<optimized out>) at /build/gcc/src/gcc/libstdc++-v3/libsupc++/eh_terminate.cc:48
#4  0x00007f2a090bbdf7 in std::terminate () at /build/gcc/src/gcc/libstdc++-v3/libsupc++/eh_terminate.cc:58
#5  0x00007f2a090bc09e in __cxxabiv1::__cxa_throw (obj=obj@entry=0x7f2a0000b830, tinfo=0x7f2a091e8268 <typeinfo for std::out_of_range>, dest=0x7f2a090d1f90 <std::out_of_range::~out_of_range()>) at /build/gcc/src/gcc/libstdc++-v3/libsupc++/eh_throw.cc:95
#6  0x00007f2a090b25ed in std::__throw_out_of_range_fmt (__fmt=<optimized out>) at /build/gcc/src/gcc/libstdc++-v3/src/c++11/functexcept.cc:82
#7  0x000055d0138c5c92 in omm::GeneralPage::about_to_accept() ()
#8  0x000055d0138cd8b5 in omm::PreferenceDialog::accept() ()
#9  0x00007f2a09e24a60 in ?? () from /usr/lib/libQt5Core.so.5
#10 0x00007f2a0aa52ef9 in ?? () from /usr/lib/libQt5Widgets.so.5
#11 0x00007f2a09e24a60 in ?? () from /usr/lib/libQt5Core.so.5
#12 0x00007f2a0a9acb83 in QAbstractButton::clicked(bool) () from /usr/lib/libQt5Widgets.so.5
#13 0x00007f2a0a9ad50c in ?? () from /usr/lib/libQt5Widgets.so.5
#14 0x00007f2a0a9aeeb3 in ?? () from /usr/lib/libQt5Widgets.so.5
#15 0x00007f2a0a9af093 in QAbstractButton::mouseReleaseEvent(QMouseEvent*) () from /usr/lib/libQt5Widgets.so.5
#16 0x00007f2a0a8fcc7e in QWidget::event(QEvent*) () from /usr/lib/libQt5Widgets.so.5
#17 0x00007f2a0a8bb702 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
#18 0x00007f2a0a8c2977 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
#19 0x00007f2a09ded7ba in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /usr/lib/libQt5Core.so.5
#20 0x00007f2a0a8c185e in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool, bool) () from /usr/lib/libQt5Widgets.so.5
#21 0x00007f2a0a9153b2 in ?? () from /usr/lib/libQt5Widgets.so.5
#22 0x00007f2a0a91878f in ?? () from /usr/lib/libQt5Widgets.so.5
#23 0x00007f2a0a8bb702 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
#24 0x00007f2a09ded7ba in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /usr/lib/libQt5Core.so.5
#25 0x00007f2a0a1c837c in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) () from /usr/lib/libQt5Gui.so.5
#26 0x00007f2a0a19db4c in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt5Gui.so.5
#27 0x00007f2a04b64c8c in ?? () from /usr/lib/libQt5XcbQpa.so.5
#28 0x00007f2a0987443c in g_main_context_dispatch () from /usr/lib/libglib-2.0.so.0
#29 0x00007f2a098c21d9 in ?? () from /usr/lib/libglib-2.0.so.0
#30 0x00007f2a09873221 in g_main_context_iteration () from /usr/lib/libglib-2.0.so.0
#31 0x00007f2a09e46331 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt5Core.so.5
#32 0x00007f2a09dec13c in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt5Core.so.5
#33 0x00007f2a0aabebaa in QDialog::exec() () from /usr/lib/libQt5Widgets.so.5
#34 0x000055d01380d9a2 in omm::Application::perform_action(QString const&) ()
#35 0x00007f2a09e24a26 in ?? () from /usr/lib/libQt5Core.so.5
#36 0x00007f2a0a8b4f23 in QAction::triggered(bool) () from /usr/lib/libQt5Widgets.so.5
#37 0x00007f2a0a8b7805 in QAction::activate(QAction::ActionEvent) () from /usr/lib/libQt5Widgets.so.5
#38 0x00007f2a0aa38f1b in ?? () from /usr/lib/libQt5Widgets.so.5
#39 0x00007f2a0aa40552 in ?? () from /usr/lib/libQt5Widgets.so.5
#40 0x00007f2a0a8fcc7e in QWidget::event(QEvent*) () from /usr/lib/libQt5Widgets.so.5
#41 0x00007f2a0a8bb702 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
#42 0x00007f2a0a8c2977 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
#43 0x00007f2a09ded7ba in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /usr/lib/libQt5Core.so.5
#44 0x00007f2a0a8c185e in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool, bool) () from /usr/lib/libQt5Widgets.so.5
#45 0x00007f2a0a91592f in ?? () from /usr/lib/libQt5Widgets.so.5
#46 0x00007f2a0a91878f in ?? () from /usr/lib/libQt5Widgets.so.5
#47 0x00007f2a0a8bb702 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
#48 0x00007f2a09ded7ba in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /usr/lib/libQt5Core.so.5
#49 0x00007f2a0a1c837c in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) () from /usr/lib/libQt5Gui.so.5
#50 0x00007f2a0a19db4c in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt5Gui.so.5
#51 0x00007f2a04b64c8c in ?? () from /usr/lib/libQt5XcbQpa.so.5
#52 0x00007f2a0987443c in g_main_context_dispatch () from /usr/lib/libglib-2.0.so.0
#53 0x00007f2a098c21d9 in ?? () from /usr/lib/libglib-2.0.so.0
#54 0x00007f2a09873221 in g_main_context_iteration () from /usr/lib/libglib-2.0.so.0
#55 0x00007f2a09e46331 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt5Core.so.5
#56 0x00007f2a09dec13c in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt5Core.so.5
#57 0x00007f2a09df45c4 in QCoreApplication::exec() () from /usr/lib/libQt5Core.so.5
#58 0x000055d013766b07 in main ()
```

**Comment by pasbi** [comment]
I can reproduce the issue now, thank you very much.
What languages can you choose in the combo box? It should be three (English, German and Spanish) but I suspect that you have zero.
The actual bug is then that you don't have any translations.

**Comment by mestaritonttu** [comment]
It has German, Spanish English. I have Finnish locale. Thanks.

**Comment by mestaritonttu** [comment]
Thanks, I confirm there is no crash anymore!

**Comment by mestaritonttu** [comment]
For the colour schemes, I think we can reach out to https://discourse.opensourcedesign.net/ after you release 1.0.
